version: '3.8'

services:
  streamlit_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - "./app:/app"  # Monta o diretório 'app' local para '/app' no contêiner
      - "teste2_baseDB:/data"  # Usa o volume Docker existente 'teste2_baseDB' em '/data' no contêiner
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLE_CORS=false
    restart: always

volumes:
  teste2_baseDB:
    external: true
