[server]
maxMessageSize = 500
headless = true
enableCORS = false
enableWebsocketCompression = false
address = "0.0.0.0"  # Permite conexões externas
port = 8501

[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
